### ISSUE TITLE
Missing Model Weights

### ISSUE THREAD

**Issue by nashit-mashkoor** [ahsan-rahim/bai-fyp#4]
Hi Ahsan,
This is absolutely great work.

But the current inference pipeline does not work since the model weights are not available. It would be really great if you could share these weights as well.

Regards,

**Comment by ahsan-rahim** [comment]
Hi Nashit, I'm glad you like our work!
I'd be happy to share the model weights, however the weights size exceeds the maximum upload size allowed on Github.

Although you can obtain those weights by training the model within this particular notebook.
Goodluck!
